Name = Intern

Flags = -std=c++98 -Wall -Werror -Wextra

Src = main.cpp Bureaucrat.cpp AForm.cpp PresidentialPardonForm.cpp RobotomyRequestForm.cpp ShrubberyCreationForm.cpp Intern.cpp

Obj = $(Src:%.cpp=%.o)

all: $(Name)

$(Name): $(Src) $(Obj)
	c++ $(Flags) $(Obj) -o $(Name)

clean:
	rm -f $(Obj)
	rm -f ShrubberyCreationForm_shrubbery

fclean: clean
	rm -f $(Name)

re: fclean all

.phony: all clean fclean re